  [31morigin/HEAD[m -> origin/main
  [31morigin/dev[m
  [31morigin/feature/admin-ui[m
  [31morigin/feature/auth[m
  [31morigin/feature/dashboard[m
  [31morigin/feature/demo-ui[m
  [31morigin/feature/flask[m
  [31morigin/feature/green-metrics[m
  [31morigin/feature/model-reliability[m
  [31morigin/feature/nurse-intake[m
  [31morigin/feature/nurse-patient-combine[m
  [31morigin/feature/patient-intake[m
  [31morigin/feature/patient-results[m
  [31morigin/feature/session-timeout[m
  [31morigin/main[m
